create database dbacademico;
show databases;
use dbacademico;
create table alunos(matricula int primary key auto_increment, nome varchar(50) not null, media DECIMAL(4,2), frequencia float);
show tables;
describe alunos;
insert into alunos (nome,media,frequencia) values ('Ana Bastos', '7', '.75');
select * from alunos;
insert into alunos (nome,media,frequencia) values ('Carlos Delfim', '7.5', '.80');
insert into alunos (nome,media,frequencia) values ('Eudes Ferreira', '8', '.85');
insert into alunos (nome,media,frequencia) values ('Gael Heron', '8.5', '.90');
insert into alunos (nome,media,frequencia) values ('Iago José', '9', '.95');